#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section




projects:

  - name: 'Portfolio'
    url: 'portfolio'
    description: 'This portfolio serves as a central hub to showcase all my projects and experiments in game development and programming. It documents my progress and serves as a personal archive.'
    repo: 'https://github.com/emr81-ua/emr81-ua.github.io'
    tech: ['Markdown', 'OpenGL', 'Jekyll', 'HTML5', 'CSS3']


  - name: 'Knightmare'
    url: 'knightmare'
    description: 'Action roguelite prototype with physics-based sword combat driven by mouse gestures.'
    tech: ['GDScript', 'Godot Engine', '2D', 'Action', 'Roguelite', 'Physics-based Combat']


  - name: 'Connect4'
    url: 'connect4'
    description: 'A C++ Connect 4 game featuring a Minimax-based AI with alpha-beta pruning and graphical interface using SFML.'
    repo: 'https://github.com/emr81-ua/Connect4'
    tech: ['C++', 'SFML', 'Minimax', 'Alpha-Beta Pruning', 'Game AI']

  - name: 'Unity project'
    url: 'proj-3'
    description: 'On development Unity project featuring a special mechanic'
    
    tech: ['C#', 'Unity']



#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://x.com/erouillion'}
- {icon: 'instagram', link: 'https://www.instagram.com/erouillion'}
- {icon: 'github',    link: 'https://github.com/emr81-ua'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/eric-muñoz-rouillion-3a303a1b2'}
- {icon: 'envelope',  link: 'mailto:ericux4@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
